import React from 'react';
import { X, ExternalLink, Music2 } from 'lucide-react';

interface DawGuideModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const DawGuideModal: React.FC<DawGuideModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fade-in font-mono">
      <div className="bg-[#0f1115] border border-zinc-700 rounded-xl max-w-2xl w-full p-6 text-zinc-300 shadow-2xl relative max-h-[90vh] overflow-y-auto">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-zinc-500 hover:text-white p-1 rounded-lg hover:bg-zinc-800 transition cursor-pointer"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center gap-2 mb-4 border-b border-zinc-800 pb-3">
          <Music2 className="w-5 h-5 text-cyan-400" />
          <h2 className="text-lg font-bold text-white uppercase tracking-wider">
            DAW MIDI Routing Guide
          </h2>
        </div>

        <div className="space-y-5 text-xs">
          {/* Ableton Section */}
          <div className="bg-zinc-950 p-4 rounded-lg border border-zinc-800">
            <h3 className="text-sm font-bold text-cyan-400 mb-2">1. Ableton Live (Live 11 / 12)</h3>
            <ol className="list-decimal list-inside space-y-1.5 text-zinc-300">
              <li>Place <strong>ChordForge VST3</strong> onto a new MIDI track (Track 1).</li>
              <li>Create a second MIDI track (Track 2) loaded with your desired instrument (e.g. Grand Piano, Serum, Wavetable).</li>
              <li>On Track 2, set <strong>MIDI From</strong> to <strong>1-ChordForge</strong>.</li>
              <li>Underneath that, select <strong>ChordForge</strong> in the channel dropdown.</li>
              <li>Set Track 2's Monitor switch to <strong>In</strong>.</li>
              <li>Press Spacebar: Track 2 will play the chords generated by ChordForge!</li>
            </ol>
          </div>

          {/* FL Studio Section */}
          <div className="bg-zinc-950 p-4 rounded-lg border border-zinc-800">
            <h3 className="text-sm font-bold text-cyan-400 mb-2">2. FL Studio (20 / 21 / 24)</h3>
            <ol className="list-decimal list-inside space-y-1.5 text-zinc-300">
              <li>In the Channel Rack, add <strong>ChordForge</strong> as an instrument generator.</li>
              <li>Open ChordForge's wrapper settings (click the <strong>Gear Icon</strong> at top left, then the <strong>VST wrapper settings</strong> tab).</li>
              <li>Under <strong>MIDI</strong>, set <strong>Output port</strong> to <strong>10</strong>.</li>
              <li>Add your synth or piano (e.g. FL Keys) to the Channel Rack.</li>
              <li>Open its wrapper settings and set <strong>Input port</strong> to <strong>10</strong>.</li>
              <li>ChordForge now drives your sound generator directly.</li>
            </ol>
          </div>

          {/* Drag & Drop vs Export */}
          <div className="bg-zinc-900/60 p-3 rounded-lg border border-zinc-800/80 text-[11px] text-zinc-400">
            <strong className="text-zinc-200">Standard MIDI Export:</strong> You can also click <strong>Export MIDI (.mid)</strong> to download a real Standard MIDI file (Format 0/1, 960 PPQ) and drag it straight onto any DAW timeline track!
          </div>
        </div>

        <div className="mt-5 text-right">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-cyan-600 hover:bg-cyan-500 text-zinc-950 font-bold rounded text-xs transition cursor-pointer"
          >
            Got It
          </button>
        </div>
      </div>
    </div>
  );
};
